import { Link } from 'react-router-dom'

function Section({ title, children }) {
  return (
    <section className="mb-8">
      <p className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#999] mb-2">{title}</p>
      <div className="text-sm text-[#333] leading-relaxed font-light space-y-3">{children}</div>
    </section>
  )
}

export default function RiskWarning() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-2xl mx-auto px-6 py-12">

        <p className="text-[10px] font-medium uppercase tracking-[0.08em] text-[#bbb] mb-6">
          <Link to="/" className="hover:text-[#666] transition-colors">Capital Lens</Link>
          {' / '}
          <span>Legal</span>
          {' / '}
          <span className="text-[#111]">Risk Warning</span>
        </p>

        <div className="border border-[#111] bg-[#fafafa] p-4 mb-8">
          <p className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#999] mb-1">
            Important
          </p>
          <p className="text-sm font-semibold text-[#111] leading-snug">
            Trading and investing carry a substantial risk of loss.
            You may lose some or all of your invested capital.
            Past performance is not a reliable indicator of future results.
          </p>
        </div>

        <h1 className="text-2xl font-bold tracking-tight text-[#111] mb-2">Risk Warning</h1>
        <p className="text-xs text-[#999] mb-10">
          Effective date: January 1, 2025 &middot; Version 1.0
        </p>

        <Section title="General Investment Risk">
          <p>
            All investments involve risk. The value of investments can fall as well as rise,
            and you may get back less than you invest. There is no guarantee that any
            investment strategy will achieve its objectives. You should never invest money
            that you cannot afford to lose.
          </p>
        </Section>

        <Section title="Equities and Market Risk">
          <p>
            Stock prices can fluctuate significantly in response to company performance,
            market conditions, economic factors, geopolitical events, and investor
            sentiment. Equity investments are not insured by any government scheme.
          </p>
        </Section>

        <Section title="Cryptocurrency and Digital Assets">
          <p>
            Cryptocurrencies and digital assets are highly volatile and speculative. They
            are not regulated investments in most jurisdictions. Prices can fall to zero.
            There is no investor protection for cryptocurrency losses. Transactions are
            generally irreversible.
          </p>
        </Section>

        <Section title="Geopolitical and Macro Risk">
          <p>
            Capital Lens aggregates geopolitical data including conflict reports, sanctions,
            and political events. This information is sourced from public databases and
            does not constitute geopolitical advice or intelligence analysis. Geopolitical
            predictions are inherently speculative and uncertain.
          </p>
        </Section>

        <Section title="Backtesting and Simulation Limitations">
          <p>
            Any backtesting or simulated performance results shown are hypothetical.
            Simulated results do not represent actual trading and have many inherent
            limitations, including:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>No accounting for real-world slippage or market impact</li>
            <li>No accounting for trading fees, taxes, or commissions</li>
            <li>Results may be influenced by hindsight bias</li>
            <li>Simulated conditions may differ materially from live markets</li>
          </ul>
        </Section>

        <Section title="Congressional Trade Data">
          <p>
            Congressional trading disclosures are public information filed under the STOCK
            Act. Capital Lens aggregates these filings for informational purposes only.
            The presence of a trade by a government official does not constitute a
            recommendation to trade the same security. Congressional trade data is
            subject to reporting delays of up to 45 days.
          </p>
        </Section>

        <Section title="AI-Generated Content">
          <p>
            Investment signals, market impact summaries, and "for you" takeaways are
            generated by large language models. AI-generated content:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>May contain factual errors, hallucinations, or outdated information</li>
            <li>Does not account for your personal financial situation</li>
            <li>Should never be acted on without independent verification</li>
            <li>Is not the opinion of a licensed financial professional</li>
          </ul>
        </Section>

        <Section title="Diversification Does Not Eliminate Risk">
          <p>
            Diversification can reduce but not eliminate investment risk. Correlations
            between assets can increase during market stress, reducing the protective
            benefit of diversification precisely when it is most needed.
          </p>
        </Section>

        <Section title="Seek Independent Advice">
          <p>
            Before making any investment decision, you should consider obtaining independent
            financial, legal, and tax advice from appropriately qualified and authorised
            professionals who understand your personal financial circumstances.
          </p>
        </Section>

        <div className="mt-12 pt-6 border-t border-[#f0f0f0] flex flex-wrap gap-4 text-[10px] font-medium uppercase tracking-[0.08em]">
          <Link to="/legal/disclaimer" className="text-[#bbb] hover:text-[#111] transition-colors">Disclaimer</Link>
          <Link to="/legal/terms"      className="text-[#bbb] hover:text-[#111] transition-colors">Terms of Service</Link>
          <Link to="/legal/privacy"    className="text-[#bbb] hover:text-[#111] transition-colors">Privacy Policy</Link>
          <Link to="/"                 className="text-[#bbb] hover:text-[#111] transition-colors ml-auto">Back to App</Link>
        </div>
      </div>
    </div>
  )
}
